services:
  # --- USER DOMAIN ---
  - type: web
    name: veloura-user-frontend-v1
    runtime: static
    staticPublishPath: ./user/frontend

  - type: web
    name: veloura-user-backend-v1
    runtime: python
    buildCommand: pip install -r user/requirements.txt
    startCommand: bash ./user/start.sh
    envVars:
      - key: PORT
        value: "5000"

  # --- ADMIN DOMAIN ---
  - type: web
    name: veloura-admin-frontend-v1
    runtime: static
    staticPublishPath: ./admin/frontend

  - type: web
    name: veloura-admin-backend-v1
    runtime: python
    buildCommand: pip install -r admin/requirements.txt
    startCommand: bash ./admin/start.sh
    envVars:
      - key: PORT
        value: "6000"
